export const guitars = [
  {
    id: "1",
    brand: "Fender",
    model: "Stratocaster",
    subModel: "ST-62DT",
    year: 1995,
    madeIn: "Japan",
    cost: 900,
    value: 1100,
    serialNumber: "SN1",
    imageUrl: "/fender.jpg",
  },
  {
    id: "2",
    brand: "Ibanez",
    model: "AZ",
    subModel: "AZ2402",
    year: 2020,
    madeIn: "Japan",
    cost: 1600,
    value: 1800,
    serialNumber: "SN2",
    imageUrl: "/ibanez_az.jpg",
  },
  {
    id: "3",
    brand: "Fender",
    model: "Stratocaster",
    year: 1994,
    madeIn: "Mexico",
    subModel: "",
    cost: 400,
    value: 400,
    serialNumber: "SN3",
    imageUrl: "/fender2.jpg",
  },
  {
    id: "4",
    brand: "Ibanez",
    model: "S",
    subModel: "S1027PBF",
    year: 2019,
    madeIn: "Indonesia",
    cost: 1100,
    value: 1200,
    serialNumber: "SN4",
    imageUrl: "/ibanez_s_7.jpg",
  },
];
